<?php

namespace App\Classes;

use App\Models\Lang;
use App\Models\Translation;
use Nwidart\Modules\Facades\Module;

class LangTrans
{
    public static $mainTranslations = [
        'common' => [
            'enabled' => 'Enabled',
            'disabled' => 'Disabled',
            'id' => 'Id',
            'action' => 'Action',
            'placeholder_default_text' => 'Please Enter {0}',
            'placeholder_social_text' => 'Please Enter {0} Url',
            'placeholder_search_text' => 'Search By {0}',
            'select_default_text' => 'Select {0}...',
            'create' => 'Create',
            'edit' => 'Edit',
            'update' => 'Update',
            'cancel' => 'Cancel',
            'delete' => 'Delete',
            'success' => 'Success',
            'error' => 'Error',
            'yes' => 'Yes',
            'no' => 'No',
            'fix_errors' => 'Please Fix Below Errors.',
            'cancelled' => 'Cancelled',
            'pending' => 'Pending',
            'paid' => 'Paid',
            'canceled' => 'Canceled',
            'completed' => 'Completed',
            'rejected' => 'Rejected',
            'save' => 'Save',
            'all' => 'All',
            'name' => 'Name',
            'back' => 'Back',
            'max_amount' => 'Max. Amount',
            'date_time' => 'Date Time',
            'select_time' => 'Select Time',
            'start_date' => 'Start Date',
            'end_date' => 'End Date',
            'search' => 'Search',
            'date' => 'Date',
            'confirm' => 'Confirm',
            'title' => 'Title',
            'value' => 'Value',
            'add' => 'Add',
            'view' => 'View',
            'download' => 'Download',
            'total' => 'Total',
            'email' => 'Email',
            'phone' => 'Phone',
            'purchase_code' => 'Purchase Code',
            'verify_purchase' => 'Verify Purchase',
            'install' => 'Install',
            'installing' => 'Installing',
            'updating' => 'Updating',
            'free' => 'Free',
            'domain' => 'Domain',
            'verify' => 'Verify',
            'send' => 'Send',
            'upload' => 'Upload',
            'view_all' => 'View All',
            'unpaid' => 'Unpaid',
            'loading' => 'Loading',
            'update_app' => 'Update App',
            'welcome_back' => 'Welcome {0}',
            'off' => 'Off',
            'on_create' => 'On Create',
            'on_update' => 'On Update',
            'on_delete' => 'On Delete',
            'demo_account_credentials' => 'Demo account login credentials',
            'created_by' => 'Created By',
            'import' => 'Import',
            'file' => 'File',
            'copy_url' => 'Copy Url',
            'print' => 'Print',
            'amount' => 'Amount',
            'status' => 'Status',
            'active' => 'Active',
            'inactive' => 'Inactive',
            'verified' => 'Verified',
            'configure' => 'Configure',
            'logo' => 'Logo',
            'slug' => 'Slug',
            'description' => 'Description',
            'image' => 'Image',
            'address' => 'Address',
            'not_allowed' => 'Not Allowed',
            'details' => 'Details',
            'text' => 'Text',
            'link' => 'Link',
            'start' => 'Start',
            'stop' => 'Stop',
            'are_you_sure' => 'Are you sure',
            'basic_details' => 'Basic Details',
            'notes' => 'Notes',
            'more' => 'More',
            'other' => 'Other',
            'continue' => 'Continue',
            'product' => 'Product',
            'service' => 'Service',
            'docs' => 'Docs',
            'sms' => 'SMS',
            'e_sign' => 'Signeasy',
            'credit_card' => 'Credit Card',
            'bank_account' => 'Bank account',
            'bank' => 'Bank',
            'debts' => 'Debts',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'close' => 'Close',
            'template_id' => 'Template ID',
            'include' => 'Include',
            'today' => 'Today',
            'create_group' => 'Create Group',
            'general' => 'General',
            'months' => 'Months',
            'monthly' => 'Monthly',
            'enrollment' => 'Enrollment',
            'unknown' => 'Unknown',
            'export' => 'Export',
            'columns' => 'Columns',
            'date_range' => 'Date Range',
            'include_all_as_default' => '(Include All As Default)',
            'payment_schedule' => 'Payment Schedule',
            'reason' => 'Reason',
            'percentage' => 'Percentage',
            'english' => 'English',
            'spanish' => 'Spanish',
        ],
        'menu' => [
            'dashboard' => 'Dashboard',
            'users' => 'Users',
            'staff_members' => 'Staff Members',
            'settings' => 'Settings',
            'company' => 'Company Settings',
            'profile' => 'Profile',
            'translations' => 'Translations',
            'languages' => 'Languages',
            'roles' => 'Role & Permissions',
            'currencies' => 'Currencies',
            'login' => 'Login',
            'logout' => 'Logout',
            'verify_product' => 'Verify Product',
            'modules' => 'Modules',
            'storage_settings' => 'Storage Settings',
            'email_settings' => 'Email Settings',
            'database_backup' => 'Database Backup',
            'companies' => 'Companies',
            'campaigns' => 'Campaigns',
            'call_manager' => 'Call Manager',
            'email_templates' => 'Email Templates',
            'sms_templates' => 'SMS Templates',
            'e_sign_templates' => 'Signeasy Templates',
            'forms'  => 'Forms',
            'form_field_names' => 'Lead Table Fields',
            'leads' => 'Leads',
            'leads_calls' => 'Leads & Calls',
            'lead_details' => 'Lead Details',
            'call_details' => 'Call Details',
            'call_logs' => 'Call Logs',
            'lead_notes' => 'Lead Notes',
            'bookings' => 'Bookings',
            'lead_sale_management' => 'Lead & Sale Management',
            'user_management' => 'User Management',
            'lead_follow_up' => 'Lead Follow Up',
            'salesmans' => 'Salesmans',
            'salesman_bookings' => 'Salesman Bookings',
            'messaging' => 'Messaging',
            'expense_categories' => 'Expense Categories',
            'expenses' => 'Expenses',
            'expense_manager' => 'Expense Manager',
            'products' => 'Products',
            'update_app' => 'Update App',
            'setup_company' => 'Setup Company',
            'sales' => 'Sales',
            'lead_status' => 'Lead Status',
            'sale_status' => 'Sale Status',
            'sale_manager' => 'Sale Manager',
            'activity_log' => 'Activity Log',
            'creditors' => 'Creditors',
            'creditor_manager' => 'Creditor Manager',
            'enrollments' => 'Enrollments',
            'enrollment_plans' => 'Enrollment Plans',
            'chat' => 'Chat',
            'templates' => 'Templates',
            'team_chat' => 'Team Chat',
            'support_chat' => 'Support Chat',
            'chat_support'  => 'Chat Support',
            'sale_management' => 'Sale Management',
            'reports' => 'Reports',
            'debts' => 'Debts Nested Tab',
            'enrollments_calendar' => 'Enrollments Calendar',
            'payment_schedules' => 'Payment Schedules',
        ],
        'dashboard' => [
            'dashboard' => 'Dashboard',
            'active_campaigns' => 'Active Campaigns',
            'call_made' => 'Call Made',
            'total_follow_up' => 'Total Follow Up',
            'total_duration' => 'Total Duration',
            'active_actioned_campaigns' => 'Active Actioned Campaigns',
        ],
        'user' => [
            'staff_members' => 'Staff Members',
            'add' => 'Add New Staff Member',
            'edit' => 'Edit Staff Member',
            'created' => 'Staff Member Created Successfully',
            'updated' => 'Staff Member Updated Successfully',
            'deleted' => 'Staff Member Deleted Successfully',
            'staff_member_details' => 'Staff Member Details',
            'staff_member' => 'Staff Member',
            'delete_message' => 'Are you sure you want to delete this staff member?',
            'selected_delete_message' => 'Are you sure you want to delete selected staff member?',
            'import_staff_members' => 'Import Staff Members',
            'email_phone' => 'Email or Phone',
            'user' => 'User',
            'name' => 'Name',
            'created_at' => 'Created At',
            'email' => 'Email',
            'password' => 'Password',
            'login_enabled' => 'Login Enabled',
            'profile_image' => 'Profile Image',
            'company_name' => 'Company Name',
            'phone' => 'Phone Number',
            'address' => 'Address',
            'city' => 'City',
            'state' => 'State',
            'country' => 'Country',
            'zipcode' => 'Zipcode',
            'status' => 'Status',
            'role' => 'Role',
            'profile_updated' => 'Profile Updated Successfully',
            'password_blank' => "Leave blank if you don't want to update password.",
            'admin_account_details' => "Admin Account Details",
            'import_users' => 'Import Users',
            'staff_members_details' => 'Staff Members Details',
            'call_log' => 'Call Log',
            'export_users' => 'Export Users',
            'time_taken' => 'Time Taken',
            'count_created_leads' => 'Count Created Leads',
            'count_last_action' => 'Count Lead/Sale Last Action',
            'count_first_action' => 'Count Lead/Sale First Action',
            'count_lead_follow_up' => 'Count Lead/Sale Follow Up',
            'count_created_sales' => 'Count Created Sales',
            'count_assigned_sales' => 'Count Assigned Sales',
            'count_sent_sms_messages' => 'Count Sent SMS Messages',
            'roles' => 'Roles',
        ],
        'role' => [
            'add' => 'Add New Role',
            'edit' => 'Edit Role',
            'created' => 'Role Created Successfully',
            'updated' => 'Role Updated Successfully',
            'deleted' => 'Role Deleted Successfully',
            'role_details' => 'Role Details',
            'delete_message' => 'Are you sure you want to delete this role?',
            'selected_delete_message' => 'Are you sure you want to delete selected role?',
            'display_name' => 'Display Name',
            'role_name' => 'Role Name',
            'description' => 'Description',
            'user_management' => 'User Management',
            'permissions' => 'Permissions',
        ],
        'notes' => [
            'add' => 'Add New Note',
            'edit' => 'Edit Note',
            'created' => 'Note Created Successfully',
            'updated' => 'Note Updated Successfully',
            'deleted' => 'Note Deleted Successfully',
            'delete_message' => 'Are you sure you want to delete this note?',
            'added_on' => 'Added On',
            'added_by' => 'Added By',
            'alert_note' => 'Set as Alert Note',
            'alert_type' => 'Alert Type',
            'standard' => 'Standard',
            'urgent' => 'Urgent',
            'escalated' => 'Escalated',
        ],
        'staff_member' => [
            'add' => 'Add New Staff Member',
            'edit' => 'Edit Staff Member',
            'created' => 'Staff Member Created Successfully',
            'updated' => 'Staff Member Updated Successfully',
            'deleted' => 'Staff Member Deleted Successfully',
            'staff_member_details' => 'Staff Member Details',
            'staff_member' => 'Staff Member',
            'delete_message' => 'Are you sure you want to delete this staff member?',
            'selected_delete_message' => 'Are you sure you want to delete selected staff member?',
            'import_staff_members' => 'Import Staff Members',
        ],
        'company' => [
            'add' => 'Add New Company',
            'edit' => 'Edit Company',
            'created' => 'Company Created Successfully',
            'updated' => 'Company Updated Successfully',
            'deleted' => 'Company Deleted Successfully',
            'delete_message' => 'Are you sure you want to delete this company?',
            'name' => 'Company Name',
            'short_name' => 'Company Short Name',
            'email' => 'Company Email',
            'phone' => 'Company Phone',
            'address' => 'Company Address',
            'logo' => 'Company Logo',
            'left_sidebar_theme' => 'Left Sidebar Theme',
            'dark' => 'Dark',
            'light' => 'Light',
            'dark_logo' => 'Dark Logo',
            'light_logo' => 'Light Logo',
            'small_dark_logo' => 'Small Dark Logo',
            'small_light_logo' => 'Small Light Logo',
            'primary_color' => 'Primary Color',
            'default_timezone' => 'Default Timezone',
            'date_format' => 'Date Format',
            'time_format' => 'Time Format',
            'auto_detect_timezone' => 'Auto Detect Timezone',
            'app_debug' => 'App Debug',
            'login_image' => 'Login Image',
            'layout' => 'Layout',
            'rtl' => 'RTL',
            'ltr' => 'LTR',
            'shortcut_menu_Placement' => 'Add Menu Placement',
            'top_and_bottom' => 'Top & Bottom',
            'top_header' => 'Top Header',
            'bottom_corner' => 'Bottom Conrer',
            'shortcut_menu_setting' => 'Add Menu Settings',
            'menu_setting_updated' => 'Menu Setting Updated',
            'basic_details' => 'Basic Details',
            'details' => 'Details',
            'register_date' => 'Register Date',
            'total_users' => 'Total Users',
            'update_app_notification' => 'Update App Notitication',
            'language' => 'Language'
        ],
        'module' => [
            'name' => 'Module Name',
            'verified' => 'Verified',
            'verify_purchase_code' => 'Verify Purchase Code',
            'current_version' => 'Current Version',
            'latest_version' => 'Latest Version',
            'status' => 'Status',
            'installed_modules' => 'Installed Modules',
            'other_modules' => 'Other Modules',
            'module_status_updated' => 'Modules Status Updated',
            'downloading_completed' => 'Download Completed',
            'extract_zip_file' => 'Extract Zip File',
            'file_extracted' => 'Zip File Extracted',
        ],
        'langs' => [
            'add' => 'Add New Language',
            'edit' => 'Edit Language',
            'details' => 'Language Details',
            'created' => 'Language Created Successfully',
            'updated' => 'Language Updated Successfully',
            'deleted' => 'Language Deleted Successfully',
            'delete_message' => 'Are you sure you want to delete this language?',
            'view_all_langs' => 'View All Languages',
            'status_updated' => 'Langugage status updated',
            'name' => 'Name',
            'key' => 'Key',
            'flag' => 'Flag',
            'enabled' => 'Enabled',
        ],
        'translations' => [
            'fetch_new_translations' => 'Fetch New Translations',
            'reload_translations' => 'Reload Translations',
            'reload_successfully' => 'Translations Reload Successfully',
            'fetched_successfully' => 'Translations Fetch Successfully',
            'import_translations' => 'Import Translations',
        ],
        'storage_settings' => [
            'updated' => 'Storage Settings Updated',
            'storage' => 'Storage',
            'local' => 'Local',
            'aws' => 'AWS S3 Storage',
            'aws_key' => 'AWS Key',
            'aws_secret' => 'AWS Secret',
            'aws_region' => 'AWS Region',
            'aws_bucket' => 'AWS Bucket',
        ],
        'mail_settings' => [
            'updated' => 'Mail Settings Updated',
            'mail_driver' => 'Mail Driver',
            'none' => 'None',
            'mail' => 'Mail',
            'smtp' => 'SMTP',
            'from_name' => 'Mail From Name',
            'from_email' => 'Mail From Email',
            'host' => 'Host',
            'port' => 'Port',
            'encryption' => 'Encryption',
            'username' => 'Username',
            'password' => 'Password',
            'send_test_mail' => 'Send Test Mail',
            'send_mail_setting_saved' => 'Send mail setting saved',
            'enable_mail_queue' => 'Enable Mail Queue',
            'send_mail_for' => 'Send Mail For',
            'email' => 'Email address for which you want to send test mail',
            'test_mail_sent_successfully' => 'Test mail sent successfully',
            'notificaiton_will_be_sent_to_company' => 'Notification will be sent to company email',
        ],
        'database_backup' => [
            'file' => 'File',
            'file_size' => 'File Size',
            'generate_backup' => 'Generate Backup',
            'delete_backup' => 'Delete Backup',
            'backup_generated_successfully' => 'Backup Generated Successfully',
            'are_you_sure_generate_backup' => 'Are you sure you want to generate database backup?',
            'are_you_sure_delete_backup' => 'Are you sure you want to delete this database backup?',
            'backup_locaion_is' => 'All generated database file will be stored in storage/app/public/backup folder. ',
            'settings' => 'Command Settings',
            'backup_command_setting' => 'Backup Command Settings',
            'mysqldump_command_path' => 'mysqldump command path',
            'command_updated' => 'Command updated successfully',
            'window_command_path' => 'If you use XAMPP then it will be => C:\xampp\mysql\bin\mysqldump.exe',
            'laragon_command_path' => 'If you use Laragon then it will be => C:\laragon\bin\mysql\mysql-5.7.24-winx64\bin\mysqldump.exe',
            'linux_command_path' => 'If you are on ubuntu or mac then run following command and enter output here => which mysqldump',
            'put_dump_path_command_on_env_file' => 'Find your MySQL dump path from below and then add it to the DUMP_PATH inside .env file',
        ],
        'update_app' => [
            'app_details' => 'App Details',
            'name' => 'Name',
            'value' => 'Value',
            'php_version' => 'PHP Version',
            'app_version' => 'App Version',
            'laravel_version' => 'Laravel Version',
            'mysql_version' => 'MySQL Version',
            'vue_version' => 'Vue Version',
            'update_app' => 'Update App',
            'update_now' => 'Update Now',
            'update_available' => 'Update Available',
            'verify_again' => 'Verify Again',
            'verify_failed' => 'Verification Failed',
            'verify_failed_message' => 'Your application is not registerd with us. Please verify it',
            'verified_with_other_domain' => 'Your purchase code is registerd with other doamin. Please verfiy your purhcase code',
        ],
        'messages' => [
            'somehing_went_wrong' => 'Something went wrong. Please contact to administrator.',
            'verify_success' => 'Successfully verified. Redirect to app...',
            'login_success' => 'Successfully login. Redirect to app...',
            'login_success_dashboard' => 'Successfully logged into app.',
            'click_here_to_find_purchase_code' => 'Click here to find your purchase code',
            'verification_successfull' => 'Verification successfully',
            'other_domain_linked' => 'Other domain linked',
            'other_domain_linked_with_purchase_code' => 'Other domain is already linked with your purchase code. Please enter your purchase code for more details...',
            'first_verify_module_message' => 'To enable please \n verify this module',
            'are_you_sure_install_message' => 'Are you sure you want to install?',
            'downloading_started_message' => 'Downloading started. Please wait ...',
            'file_extracting_message' => 'File extracteding. Please wait ...',
            'installation_success' => 'Installation successfully. Click here to reload page...',
            'are_you_sure_update_message' => 'Are you sure you want to update? Please take backup before update.',
            'stmp_success_message' => 'Your SMTP settings are correct..',
            'stmp_error_message' => 'Your SMTP settings are incorrect. Please update it to send mails',
            'uploading_failed' => 'Uploading failed',
            'loading_app_message' => 'Loading... Please wait',
            'fetching_product_details' => 'We are fetching product details. Please wait...',
            'product_is_upto_date' => 'You are on the latest version of app.',
            'new_app_version_avaialbe' => 'New app version {0} is available. Please update to get latest version.',
            'not_able_to_edit_order' => 'Only order status editable, other fields can not be editable becuase this order linked to some payments. Delete those payment(s) and try again.',
            'click_here_to_download_sample_file' => 'Click here to download sample csv file',
            'imported_successfully' => 'Imported Successfully',
            'company_admin_password_message' => 'Admin will login using this password. (Leave blank to keep current password)',
            'email_setting_not_configured' => 'Email setting not configured',
            'please_configure_email_settings' => 'Please configure your email settings to send emails. Click Here to configure email settings.',
        ],
        'popover' => [
            'auto_detect_timezone' => 'Allow auto detect timezone from browser for currently logged in user.',
            'click_here_to_copy_credentials' => 'Click here to copy {0} credentials',
        ],
        'topbar_add_button' => [
            'add_staff_member' => 'Add Staff Member',
            'add_language' => 'Add Language',
            'add_role' => 'Add Role',
        ],
        'setup_company' => [
            'setup_not_completed' => 'Setup Not Completed',
            'setup_not_completed_description' => 'Your company default settings not completed. Follow below setups to complete your company basic settings...',
            'company_settings' => 'Company Settings',
            'set_company_basic_settings' => 'Setup Company Basic Settings',
            'previous_step' => 'Previous Step',
            'next_step' => 'Next Step',
            'basic_settings' => 'Basic Settings',
            'theme_settings' => 'Theme Settings',
            'logo_settings' => 'Logo Settings',
            'save_finish_setup' => 'Save & Finish Setup',
            'go_to_dashboard' => 'Go To Dashboard',
            'setup_running_message' => 'Please wait... we are setting up inital company settings.',
            'setup_complete_message' => 'Setup completed... Click on below link to view your app...',
        ],
        'activity_log' => [
            'contact_reference' => 'Contact Reference Number',
            'entity' => 'entity',
            'timestamp' => 'Timestamp',
            'user' => 'User',
            'details' => 'Details',
            'call' => 'Call',
            'follow_up' => 'Follow Up',
            'salesman_booking' => 'Salesman Booking',
            'lead' => 'Lead',
            'doc' => 'Doc',
            'email' => 'Email',
            'sms' => 'SMS',
            'card' => 'Card',
            'bank' => 'Bank',
            'note' => 'Note',
            'debt' => 'Debt',
            'lead_updated' => 'Lead Updated',
            'co_applicant_added' => 'Co-Applicant Added',
            'co_applicant_updated' => 'Co-Applicant Updated',
            'co_address_added' => 'Co-Applicant Address Added',
            'co_address_updated' => 'Co-Applicant Address Updated',
            'address_added' => 'Address Added',
            'address_updated' => 'Address Updated',
            'lead_reassigned' => 'Lead reassigned from {0} to {1}',
            'lead_update_status' => 'Lead status updated to {0}',
            'doc_uploaded' => 'Doc Uploaded',
            'doc_deleted' => 'Doc Deleted',
            'doc_generated' => 'Doc Generated',
            'doc_esign' => 'Doc Sent via Signeasy',
            'card_created' => 'Card Created',
            'card_updated' => 'Card Updated',
            'card_deleted' => 'Card Deleted',
            'bank_account_created' => 'Bank Account Created',
            'bank_account_updated' => 'Bank Account Updated',
            'bank_account_deleted' => 'Bank Account Deleted',
            'note_created' => 'Note Created',
            'note_updated' => 'Note Updated',
            'note_deleted' => 'Note Deleted',
            'debt_note_created' => 'Debt Note Created',
            'debt_note_updated' => 'Debt Note Updated',
            'debt_note_deleted' => 'Debt Note Deleted',
            'follow_up_created' => 'Follow Up Created',
            'follow_up_deleted' => 'Follow Up Deleted',
            'salesman_booking_created' => 'Salesman Booking Created',
            'salesman_booking_deleted' => 'Salesman Booking Deleted',
            'email_sent' => 'Email Sent',
            'sms_sent' => 'SMS Sent',
            'call_made' => 'Call made with a duration of {0}',
            'more_details' => 'More Details',
            'notes' => 'Notes',

            'first_name' => 'First Name',
            'last_name' => 'Last Name',
            'SSN' => 'SSN',
            'date_of_birth' => 'Date of Birth',
            'language' => 'Language',
            'original_profile_id' => 'Original Profile ID',

            'payment_type' => 'Payment Type',
            'card_type' => 'Card type',
            'card_issuer' => 'Card Issuer',
            'name_on_card' => 'Name On Card',
            'card_number' => 'Card Number',
            'expiration_date' => 'Expiration date',
            'CVV' => 'CVV',
            'address_line1' => 'Address',
            'address_line2' => 'Address 2',
            'city' => 'City',
            'state_id' => 'State',
            'zip_code' => 'Zip',

            'routing_number' => 'Routing Number',
            'account_number' => 'Account Number',
            'account_type' => 'Account Type',
            'bank_name' => 'Bank Name',
            'account_holder_name' => 'Account Holder Name',
            'account_holder_address' => 'Account Holder Address',
            'account_holder_city' => 'Account Holder City',
            'account_holder_state' => 'Account Holder State',
            'account_holder_zipcode' => 'Account Holder Zipcode',
            'title' => 'Title',
            'type' => 'Type',
            'phone_number' => 'Phone Number',
            'home_phone' => 'Home Phone',
            'message' => 'Message',

            'amount' => 'Amount',
            'enrolled_status' => 'Enrolled Status',
            'creditor' => 'Creditor',
            'collection' => 'Collection',
            'account' => 'Account',
            'debt_type' => 'Debt Type',
            'current_amount' => 'Current Amount',
            'whose_debt' => 'Whose Debt',
            'current_payment' => 'Current Payment',
            'last_payment_date' => 'Last Payment Date',
            'settlement' => 'Settlement',

            'creditor_id' => 'Creditor',
            'debt_buyer_id' => 'Debt Buyer',
            'third_party_account' => 'Third Party Account',
            'debt_type_id' => 'Debt Type',
            'original_amount' => 'Original Amount',
            'verified_amount' => 'Verified Amount',
            'verified_date' => 'Verified Date',
            'current_interest_rate' => 'Current Interest Rate',
            'negotiated_interest_rate' => 'Negotiated Interest Rate',

            'debt_created' => 'Debt Created',
            'debt_updated' => 'Debt Updated',
            'enrollment' => 'Enrollment',
            'enrollment_created' => 'Enrollment Created',
            'enrollment_updated' => 'Enrollment Updated',

            'document_voided' => 'Document was voided',
            'document_signed' => 'Document was signed',

            'sales_export' => 'Sales was Exported',
            'leads_export' => 'Leads was Exported',
            'staff_members_export' => 'Staff Members was Exported',
            'payment_method' => 'Payment Method',

            'enrollment_plan_id' => 'Enrollment Plan',
            'interest_rate' => 'Interest Rate',
            'enrollment_term' => 'Enrollment Term',
            'start_date' => 'Start Date',
            'onboarding_fee' => 'Onboarding Fee',
            'additional_fee' => 'Additional Fee',
            'total_debt' => 'Total Debt',
            'enrollment_deleted' => 'Enrollment Deleted',

            'content' => 'Content',
            'alert_type' => 'Alert Type',
        ],
        'team_chat' => [
            'add' => 'New Chat',
            'today' => 'Today',
        ],
        'notification' => [
            'notifications' => 'Notifications',
            'mark_all_as_read' => 'Mark All As Read',
            'view_all_notifications' => 'View All Notifications',
            'load_more' => 'Load More',
            'sale_transfer' => '{0} transferred {1} sales to your account',
            'signed_document' => "{0}'s document, {1}, is fully signed",
        ]
    ];

    public static $eStoreTranslations = [];

    public static function getTranslationArray($moduleName)
    {
        if ($moduleName == 'Estore') {
            return self::$eStoreTranslations;
        } else if ($moduleName == 'Superadmin') {
            return \App\SuperAdmin\Classes\SuperAdminLangTrans::$mainTranslations;
        }

        return self::$mainTranslations;
    }

    public static function seedTranslations($moduleName = '')
    {
        $allLangs = Lang::all();

        $translations = self::getTranslationArray($moduleName);

        foreach ($translations as $group => $translation) {
            foreach ($translation as $transKey => $transValue) {

                foreach ($allLangs as $allLang) {
                    $translationCount = Translation::where('lang_id', $allLang->id)
                        ->where('group', $group)
                        ->where('key', $transKey)
                        ->count();

                    if ($translationCount == 0) {
                        $newTranslation = new Translation();
                        $newTranslation->lang_id = $allLang->id;
                        $newTranslation->group = $group;
                        $newTranslation->key = $transKey;
                        $newTranslation->value = $transValue;
                        $newTranslation->save();
                    }
                }
            }
        }
    }

    public static function seedMainTranslations()
    {
        // Main Module
        self::seedTranslations();

        // Seeding modules
        self::seedAllModulesTranslations();
    }

    public static function seedAllModulesTranslations()
    {
        $allModules = Module::all();
        foreach ($allModules as $allModule) {
            self::seedTranslations($allModule);
        }
    }
}
